services:
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local
    env_file:
      - .env.development
    environment:
      - DRIVER=serverless
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      target: dev
    container_name: acquisitions-api-dev
    env_file:
      - .env.development
    ports:
      - '3000:3000'
    depends_on:
      - neon-local
    volumes:
      - .:/app
      - /app/node_modules
